name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  nightly-version: nightly-2022-08-29
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/chiselstrike/rust-build-image:v1.0
      options: --user 1000
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          components: rustfmt, clippy

    - uses: actions/setup-node@v3
      with:
          node-version: 16

    - name: Install nightly rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ env.nightly-version }}
          components: rustfmt, clippy

    - name: set up cache
      uses: Swatinem/rust-cache@v1
      with:
          key: ${{ env.nightly-version }}

    - name: set up node cache
      uses: actions/cache@v2
      with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Cargo config
      run: |
          mkdir -p ~/.cargo
          cp scripts/cargo-config.toml ~/.cargo/config.toml

    - name: Build debug mode binaries
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose

    - name: Build cli in isolation
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose -p cli

    - name: Build server in isolation
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose -p server

    - name: run unit tests
      uses: actions-rs/cargo@v1
      timeout-minutes: 20
      with:
          command: test

  postgres-test:
    runs-on: self-hosted
    container:
      image: ghcr.io/chiselstrike/rust-build-image:v1.0
      options: --user 1000
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          components: rustfmt, clippy

    - name: Configure Rust cache
      uses: Swatinem/rust-cache@v1

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Configure Node cache
      uses: actions/cache@v2
      with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Cargo config
      run: |
          mkdir -p ~/.cargo
          cp scripts/cargo-config.toml ~/.cargo/config.toml

    - name: Run integration tests against Postgres
      uses: actions-rs/cargo@v1
      timeout-minutes: 20
      with:
          command: test
          args: -p cli --test integration_tests -- --database postgres --database-user postgres --database-password "$POSTGRES_PASSWORD" --database-host postgres
